// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

// Hub marks this type as a conversion hub.
func (tr *Community) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *Firewall) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *Instance) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *MaintenanceWindow) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *Plugin) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *VPC) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *VpcPeering) Hub() {}
