// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
)

type PluginInitParameters struct {

	// Enable or disable the plugins.
	// If the plugin is enabled
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`

	// The CloudAMQP instance ID.
	// Instance identifier
	InstanceID *float64 `json:"instanceId,omitempty" tf:"instance_id,omitempty"`

	// The name of the Rabbit MQ plugin.
	// The name of the plugin
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// Configurable sleep time (seconds) for retries when requesting
	// information about plugins. Default set to 10 seconds.
	// Configurable sleep time in seconds between retries for plugins
	Sleep *float64 `json:"sleep,omitempty" tf:"sleep,omitempty"`

	// Configurable timeout time (seconds) for retries when requesting
	// information about plugins. Default set to 1800 seconds.
	// Configurable timeout time in seconds for plugins
	Timeout *float64 `json:"timeout,omitempty" tf:"timeout,omitempty"`
}

type PluginObservation struct {

	// The description of the plugin.
	// The description of the plugin
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// Enable or disable the plugins.
	// If the plugin is enabled
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`

	// The identifier for this resource.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// The CloudAMQP instance ID.
	// Instance identifier
	InstanceID *float64 `json:"instanceId,omitempty" tf:"instance_id,omitempty"`

	// The name of the Rabbit MQ plugin.
	// The name of the plugin
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// Configurable sleep time (seconds) for retries when requesting
	// information about plugins. Default set to 10 seconds.
	// Configurable sleep time in seconds between retries for plugins
	Sleep *float64 `json:"sleep,omitempty" tf:"sleep,omitempty"`

	// Configurable timeout time (seconds) for retries when requesting
	// information about plugins. Default set to 1800 seconds.
	// Configurable timeout time in seconds for plugins
	Timeout *float64 `json:"timeout,omitempty" tf:"timeout,omitempty"`

	// The version of the plugin.
	// The version of the plugin
	Version *string `json:"version,omitempty" tf:"version,omitempty"`
}

type PluginParameters struct {

	// Enable or disable the plugins.
	// If the plugin is enabled
	// +kubebuilder:validation:Optional
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`

	// The CloudAMQP instance ID.
	// Instance identifier
	// +kubebuilder:validation:Optional
	InstanceID *float64 `json:"instanceId,omitempty" tf:"instance_id,omitempty"`

	// The name of the Rabbit MQ plugin.
	// The name of the plugin
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// Configurable sleep time (seconds) for retries when requesting
	// information about plugins. Default set to 10 seconds.
	// Configurable sleep time in seconds between retries for plugins
	// +kubebuilder:validation:Optional
	Sleep *float64 `json:"sleep,omitempty" tf:"sleep,omitempty"`

	// Configurable timeout time (seconds) for retries when requesting
	// information about plugins. Default set to 1800 seconds.
	// Configurable timeout time in seconds for plugins
	// +kubebuilder:validation:Optional
	Timeout *float64 `json:"timeout,omitempty" tf:"timeout,omitempty"`
}

// PluginSpec defines the desired state of Plugin
type PluginSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     PluginParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider PluginInitParameters `json:"initProvider,omitempty"`
}

// PluginStatus defines the observed state of Plugin.
type PluginStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        PluginObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// Plugin is the Schema for the Plugins API. Enable and disable Rabbit MQ plugin.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,cloudamqp}
type Plugin struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.enabled) || (has(self.initProvider) && has(self.initProvider.enabled))",message="spec.forProvider.enabled is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.instanceId) || (has(self.initProvider) && has(self.initProvider.instanceId))",message="spec.forProvider.instanceId is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.name) || (has(self.initProvider) && has(self.initProvider.name))",message="spec.forProvider.name is a required parameter"
	Spec   PluginSpec   `json:"spec"`
	Status PluginStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// PluginList contains a list of Plugins
type PluginList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []Plugin `json:"items"`
}

// Repository type metadata.
var (
	Plugin_Kind             = "Plugin"
	Plugin_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: Plugin_Kind}.String()
	Plugin_KindAPIVersion   = Plugin_Kind + "." + CRDGroupVersion.String()
	Plugin_GroupVersionKind = CRDGroupVersion.WithKind(Plugin_Kind)
)

func init() {
	SchemeBuilder.Register(&Plugin{}, &PluginList{})
}
