// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
	v2 "github.com/crossplane/crossplane-runtime/v2/apis/common/v2"
)

type AzureMonitorInitParameters struct {

	// Azure Application Insights Connection String for authentication.
	// Azure Application Insights Connection String
	ConnectionStringSecretRef v1.LocalSecretKeySelector `json:"connectionStringSecretRef" tf:"-"`
}

type AzureMonitorObservation struct {
}

type AzureMonitorParameters struct {

	// Azure Application Insights Connection String for authentication.
	// Azure Application Insights Connection String
	// +kubebuilder:validation:Optional
	ConnectionStringSecretRef v1.LocalSecretKeySelector `json:"connectionStringSecretRef" tf:"-"`
}

type CloudwatchV3InitParameters struct {

	// AWS IAM external ID for role assumption.
	// External identifier that matches the role you created.
	IAMExternalID *string `json:"iamExternalId,omitempty" tf:"iam_external_id,omitempty"`

	// AWS IAM role ARN with PutMetricData permission for CloudWatch integration.
	// AWS IAM role ARN with PutMetricData permission
	IAMRole *string `json:"iamRole,omitempty" tf:"iam_role,omitempty"`

	// Datadog region code. Valid values: us1, us3, us5, eu1.
	// AWS region
	Region *string `json:"region,omitempty" tf:"region,omitempty"`

	// Additional tags to attach to metrics. Format: key=value,key2=value2.
	// tags. E.g. env=prod,service=web
	Tags *string `json:"tags,omitempty" tf:"tags,omitempty"`
}

type CloudwatchV3Observation struct {

	// AWS IAM external ID for role assumption.
	// External identifier that matches the role you created.
	IAMExternalID *string `json:"iamExternalId,omitempty" tf:"iam_external_id,omitempty"`

	// AWS IAM role ARN with PutMetricData permission for CloudWatch integration.
	// AWS IAM role ARN with PutMetricData permission
	IAMRole *string `json:"iamRole,omitempty" tf:"iam_role,omitempty"`

	// Datadog region code. Valid values: us1, us3, us5, eu1.
	// AWS region
	Region *string `json:"region,omitempty" tf:"region,omitempty"`

	// Additional tags to attach to metrics. Format: key=value,key2=value2.
	// tags. E.g. env=prod,service=web
	Tags *string `json:"tags,omitempty" tf:"tags,omitempty"`
}

type CloudwatchV3Parameters struct {

	// AWS IAM external ID for role assumption.
	// External identifier that matches the role you created.
	// +kubebuilder:validation:Optional
	IAMExternalID *string `json:"iamExternalId" tf:"iam_external_id,omitempty"`

	// AWS IAM role ARN with PutMetricData permission for CloudWatch integration.
	// AWS IAM role ARN with PutMetricData permission
	// +kubebuilder:validation:Optional
	IAMRole *string `json:"iamRole" tf:"iam_role,omitempty"`

	// Datadog region code. Valid values: us1, us3, us5, eu1.
	// AWS region
	// +kubebuilder:validation:Optional
	Region *string `json:"region" tf:"region,omitempty"`

	// Additional tags to attach to metrics. Format: key=value,key2=value2.
	// tags. E.g. env=prod,service=web
	// +kubebuilder:validation:Optional
	Tags *string `json:"tags,omitempty" tf:"tags,omitempty"`
}

type DatadogV3InitParameters struct {

	// New Relic API key for authentication.
	APIKeySecretRef v1.LocalSecretKeySelector `json:"apiKeySecretRef" tf:"-"`

	// Enable metric name transformation to match Datadog's RabbitMQ dashboard format. Default: false. Note: This option is only available for RabbitMQ clusters, not LavinMQ clusters.
	// Enable metric name transformation to match Datadog's RabbitMQ dashboard format
	RabbitmqDashboardMetricsFormat *bool `json:"rabbitmqDashboardMetricsFormat,omitempty" tf:"rabbitmq_dashboard_metrics_format,omitempty"`

	// Datadog region code. Valid values: us1, us3, us5, eu1.
	// Datadog region; us1, us3, us5, or eu1
	Region *string `json:"region,omitempty" tf:"region,omitempty"`

	// Additional tags to attach to metrics. Format: key=value,key2=value2.
	// tags. E.g. env=prod,service=web
	Tags *string `json:"tags,omitempty" tf:"tags,omitempty"`
}

type DatadogV3Observation struct {

	// Enable metric name transformation to match Datadog's RabbitMQ dashboard format. Default: false. Note: This option is only available for RabbitMQ clusters, not LavinMQ clusters.
	// Enable metric name transformation to match Datadog's RabbitMQ dashboard format
	RabbitmqDashboardMetricsFormat *bool `json:"rabbitmqDashboardMetricsFormat,omitempty" tf:"rabbitmq_dashboard_metrics_format,omitempty"`

	// Datadog region code. Valid values: us1, us3, us5, eu1.
	// Datadog region; us1, us3, us5, or eu1
	Region *string `json:"region,omitempty" tf:"region,omitempty"`

	// Additional tags to attach to metrics. Format: key=value,key2=value2.
	// tags. E.g. env=prod,service=web
	Tags *string `json:"tags,omitempty" tf:"tags,omitempty"`
}

type DatadogV3Parameters struct {

	// New Relic API key for authentication.
	// +kubebuilder:validation:Optional
	APIKeySecretRef v1.LocalSecretKeySelector `json:"apiKeySecretRef" tf:"-"`

	// Enable metric name transformation to match Datadog's RabbitMQ dashboard format. Default: false. Note: This option is only available for RabbitMQ clusters, not LavinMQ clusters.
	// Enable metric name transformation to match Datadog's RabbitMQ dashboard format
	// +kubebuilder:validation:Optional
	RabbitmqDashboardMetricsFormat *bool `json:"rabbitmqDashboardMetricsFormat,omitempty" tf:"rabbitmq_dashboard_metrics_format,omitempty"`

	// Datadog region code. Valid values: us1, us3, us5, eu1.
	// Datadog region; us1, us3, us5, or eu1
	// +kubebuilder:validation:Optional
	Region *string `json:"region" tf:"region,omitempty"`

	// Additional tags to attach to metrics. Format: key=value,key2=value2.
	// tags. E.g. env=prod,service=web
	// +kubebuilder:validation:Optional
	Tags *string `json:"tags,omitempty" tf:"tags,omitempty"`
}

type DynatraceInitParameters struct {

	// Dynatrace access token with 'Ingest metrics' permission.
	// Dynatrace access token with 'Ingest metrics' permission
	AccessTokenSecretRef v1.LocalSecretKeySelector `json:"accessTokenSecretRef" tf:"-"`

	// Dynatrace environment ID.
	// Dynatrace environment ID
	EnvironmentID *string `json:"environmentId,omitempty" tf:"environment_id,omitempty"`

	// Additional tags to attach to metrics. Format: key=value,key2=value2.
	// tags. E.g. env=prod,service=web
	Tags *string `json:"tags,omitempty" tf:"tags,omitempty"`
}

type DynatraceObservation struct {

	// Dynatrace environment ID.
	// Dynatrace environment ID
	EnvironmentID *string `json:"environmentId,omitempty" tf:"environment_id,omitempty"`

	// Additional tags to attach to metrics. Format: key=value,key2=value2.
	// tags. E.g. env=prod,service=web
	Tags *string `json:"tags,omitempty" tf:"tags,omitempty"`
}

type DynatraceParameters struct {

	// Dynatrace access token with 'Ingest metrics' permission.
	// Dynatrace access token with 'Ingest metrics' permission
	// +kubebuilder:validation:Optional
	AccessTokenSecretRef v1.LocalSecretKeySelector `json:"accessTokenSecretRef" tf:"-"`

	// Dynatrace environment ID.
	// Dynatrace environment ID
	// +kubebuilder:validation:Optional
	EnvironmentID *string `json:"environmentId" tf:"environment_id,omitempty"`

	// Additional tags to attach to metrics. Format: key=value,key2=value2.
	// tags. E.g. env=prod,service=web
	// +kubebuilder:validation:Optional
	Tags *string `json:"tags,omitempty" tf:"tags,omitempty"`
}

type IntegrationPrometheusInitParameters struct {
	AzureMonitor []AzureMonitorInitParameters `json:"azureMonitor,omitempty" tf:"azure_monitor,omitempty"`

	CloudwatchV3 []CloudwatchV3InitParameters `json:"cloudwatchV3,omitempty" tf:"cloudwatch_v3,omitempty"`

	DatadogV3 []DatadogV3InitParameters `json:"datadogV3,omitempty" tf:"datadog_v3,omitempty"`

	Dynatrace []DynatraceInitParameters `json:"dynatrace,omitempty" tf:"dynatrace,omitempty"`

	// Instance identifier for the CloudAMQP instance.
	// Instance identifier
	// +crossplane:generate:reference:type=github.com/evaneos/provider-cloudamqp/apis/namespaced/cloudamqp/v1alpha1.Instance
	InstanceID *float64 `json:"instanceId,omitempty" tf:"instance_id,omitempty"`

	// Reference to a Instance in cloudamqp to populate instanceId.
	// +kubebuilder:validation:Optional
	InstanceIDRef *v1.NamespacedReference `json:"instanceIdRef,omitempty" tf:"-"`

	// Selector for a Instance in cloudamqp to populate instanceId.
	// +kubebuilder:validation:Optional
	InstanceIDSelector *v1.NamespacedSelector `json:"instanceIdSelector,omitempty" tf:"-"`

	// List of metrics to include in the integration. If not specified, default metrics are included.
	// For more information about metrics filtering, see the metrics filtering documentation.
	// List of metrics to include. If not specified, default metrics are used. See https://www.cloudamqp.com/docs/monitoring_metrics_splunk_v2.html#metrics-filtering for more information
	MetricsFilter []*string `json:"metricsFilter,omitempty" tf:"metrics_filter,omitempty"`

	NewrelicV3 []NewrelicV3InitParameters `json:"newrelicV3,omitempty" tf:"newrelic_v3,omitempty"`

	SplunkV2 []SplunkV2InitParameters `json:"splunkV2,omitempty" tf:"splunk_v2,omitempty"`

	StackdriverV2 []StackdriverV2InitParameters `json:"stackdriverV2,omitempty" tf:"stackdriver_v2,omitempty"`
}

type IntegrationPrometheusObservation struct {
	AzureMonitor []AzureMonitorParameters `json:"azureMonitor,omitempty" tf:"azure_monitor,omitempty"`

	CloudwatchV3 []CloudwatchV3Observation `json:"cloudwatchV3,omitempty" tf:"cloudwatch_v3,omitempty"`

	DatadogV3 []DatadogV3Observation `json:"datadogV3,omitempty" tf:"datadog_v3,omitempty"`

	Dynatrace []DynatraceObservation `json:"dynatrace,omitempty" tf:"dynatrace,omitempty"`

	// The integration identifier.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// Instance identifier for the CloudAMQP instance.
	// Instance identifier
	InstanceID *float64 `json:"instanceId,omitempty" tf:"instance_id,omitempty"`

	// List of metrics to include in the integration. If not specified, default metrics are included.
	// For more information about metrics filtering, see the metrics filtering documentation.
	// List of metrics to include. If not specified, default metrics are used. See https://www.cloudamqp.com/docs/monitoring_metrics_splunk_v2.html#metrics-filtering for more information
	MetricsFilter []*string `json:"metricsFilter,omitempty" tf:"metrics_filter,omitempty"`

	NewrelicV3 []NewrelicV3Observation `json:"newrelicV3,omitempty" tf:"newrelic_v3,omitempty"`

	SplunkV2 []SplunkV2Observation `json:"splunkV2,omitempty" tf:"splunk_v2,omitempty"`

	StackdriverV2 []StackdriverV2Observation `json:"stackdriverV2,omitempty" tf:"stackdriver_v2,omitempty"`
}

type IntegrationPrometheusParameters struct {

	// +kubebuilder:validation:Optional
	AzureMonitor []AzureMonitorParameters `json:"azureMonitor,omitempty" tf:"azure_monitor,omitempty"`

	// +kubebuilder:validation:Optional
	CloudwatchV3 []CloudwatchV3Parameters `json:"cloudwatchV3,omitempty" tf:"cloudwatch_v3,omitempty"`

	// +kubebuilder:validation:Optional
	DatadogV3 []DatadogV3Parameters `json:"datadogV3,omitempty" tf:"datadog_v3,omitempty"`

	// +kubebuilder:validation:Optional
	Dynatrace []DynatraceParameters `json:"dynatrace,omitempty" tf:"dynatrace,omitempty"`

	// Instance identifier for the CloudAMQP instance.
	// Instance identifier
	// +crossplane:generate:reference:type=github.com/evaneos/provider-cloudamqp/apis/namespaced/cloudamqp/v1alpha1.Instance
	// +kubebuilder:validation:Optional
	InstanceID *float64 `json:"instanceId,omitempty" tf:"instance_id,omitempty"`

	// Reference to a Instance in cloudamqp to populate instanceId.
	// +kubebuilder:validation:Optional
	InstanceIDRef *v1.NamespacedReference `json:"instanceIdRef,omitempty" tf:"-"`

	// Selector for a Instance in cloudamqp to populate instanceId.
	// +kubebuilder:validation:Optional
	InstanceIDSelector *v1.NamespacedSelector `json:"instanceIdSelector,omitempty" tf:"-"`

	// List of metrics to include in the integration. If not specified, default metrics are included.
	// For more information about metrics filtering, see the metrics filtering documentation.
	// List of metrics to include. If not specified, default metrics are used. See https://www.cloudamqp.com/docs/monitoring_metrics_splunk_v2.html#metrics-filtering for more information
	// +kubebuilder:validation:Optional
	MetricsFilter []*string `json:"metricsFilter,omitempty" tf:"metrics_filter,omitempty"`

	// +kubebuilder:validation:Optional
	NewrelicV3 []NewrelicV3Parameters `json:"newrelicV3,omitempty" tf:"newrelic_v3,omitempty"`

	// +kubebuilder:validation:Optional
	SplunkV2 []SplunkV2Parameters `json:"splunkV2,omitempty" tf:"splunk_v2,omitempty"`

	// +kubebuilder:validation:Optional
	StackdriverV2 []StackdriverV2Parameters `json:"stackdriverV2,omitempty" tf:"stackdriver_v2,omitempty"`
}

type NewrelicV3InitParameters struct {

	// New Relic API key for authentication.
	APIKeySecretRef v1.LocalSecretKeySelector `json:"apiKeySecretRef" tf:"-"`

	// Additional tags to attach to metrics. Format: key=value,key2=value2.
	// tags. E.g. env=prod,service=web
	Tags *string `json:"tags,omitempty" tf:"tags,omitempty"`
}

type NewrelicV3Observation struct {

	// Additional tags to attach to metrics. Format: key=value,key2=value2.
	// tags. E.g. env=prod,service=web
	Tags *string `json:"tags,omitempty" tf:"tags,omitempty"`
}

type NewrelicV3Parameters struct {

	// New Relic API key for authentication.
	// +kubebuilder:validation:Optional
	APIKeySecretRef v1.LocalSecretKeySelector `json:"apiKeySecretRef" tf:"-"`

	// Additional tags to attach to metrics. Format: key=value,key2=value2.
	// tags. E.g. env=prod,service=web
	// +kubebuilder:validation:Optional
	Tags *string `json:"tags,omitempty" tf:"tags,omitempty"`
}

type SplunkV2InitParameters struct {

	// Splunk HEC endpoint URL. Example: https://your-instance-id.splunkcloud.com:8088/services/collector.
	// Splunk HEC endpoint. E.g. https://your-instance-id.splunkcloud.com:8088/services/collector
	Endpoint *string `json:"endpoint,omitempty" tf:"endpoint,omitempty"`

	// Additional tags to attach to metrics. Format: key=value,key2=value2.
	// tags. E.g. env=prod,service=web
	Tags *string `json:"tags,omitempty" tf:"tags,omitempty"`

	// Splunk HEC (HTTP Event Collector) token for authentication.
	// Splunk HEC token
	TokenSecretRef v1.LocalSecretKeySelector `json:"tokenSecretRef" tf:"-"`
}

type SplunkV2Observation struct {

	// Splunk HEC endpoint URL. Example: https://your-instance-id.splunkcloud.com:8088/services/collector.
	// Splunk HEC endpoint. E.g. https://your-instance-id.splunkcloud.com:8088/services/collector
	Endpoint *string `json:"endpoint,omitempty" tf:"endpoint,omitempty"`

	// Additional tags to attach to metrics. Format: key=value,key2=value2.
	// tags. E.g. env=prod,service=web
	Tags *string `json:"tags,omitempty" tf:"tags,omitempty"`
}

type SplunkV2Parameters struct {

	// Splunk HEC endpoint URL. Example: https://your-instance-id.splunkcloud.com:8088/services/collector.
	// Splunk HEC endpoint. E.g. https://your-instance-id.splunkcloud.com:8088/services/collector
	// +kubebuilder:validation:Optional
	Endpoint *string `json:"endpoint" tf:"endpoint,omitempty"`

	// Additional tags to attach to metrics. Format: key=value,key2=value2.
	// tags. E.g. env=prod,service=web
	// +kubebuilder:validation:Optional
	Tags *string `json:"tags,omitempty" tf:"tags,omitempty"`

	// Splunk HEC (HTTP Event Collector) token for authentication.
	// Splunk HEC token
	// +kubebuilder:validation:Optional
	TokenSecretRef v1.LocalSecretKeySelector `json:"tokenSecretRef" tf:"-"`
}

type StackdriverV2InitParameters struct {

	// Base64-encoded Google service account key JSON file with 'Monitoring Metric Writer' permission.
	// Base64-encoded Google service account key JSON file
	CredentialsFileSecretRef v1.LocalSecretKeySelector `json:"credentialsFileSecretRef" tf:"-"`

	// Additional tags to attach to metrics. Format: key=value,key2=value2.
	// tags. E.g. env=prod,service=web
	Tags *string `json:"tags,omitempty" tf:"tags,omitempty"`
}

type StackdriverV2Observation struct {

	// Google service account client email extracted from the credentials file.
	// Google service account client email (computed from credentials file)
	ClientEmail *string `json:"clientEmail,omitempty" tf:"client_email,omitempty"`

	// Google Cloud project ID extracted from the credentials file.
	// Google Cloud project ID (computed from credentials file)
	ProjectID *string `json:"projectId,omitempty" tf:"project_id,omitempty"`

	// Additional tags to attach to metrics. Format: key=value,key2=value2.
	// tags. E.g. env=prod,service=web
	Tags *string `json:"tags,omitempty" tf:"tags,omitempty"`
}

type StackdriverV2Parameters struct {

	// Base64-encoded Google service account key JSON file with 'Monitoring Metric Writer' permission.
	// Base64-encoded Google service account key JSON file
	// +kubebuilder:validation:Optional
	CredentialsFileSecretRef v1.LocalSecretKeySelector `json:"credentialsFileSecretRef" tf:"-"`

	// Additional tags to attach to metrics. Format: key=value,key2=value2.
	// tags. E.g. env=prod,service=web
	// +kubebuilder:validation:Optional
	Tags *string `json:"tags,omitempty" tf:"tags,omitempty"`
}

// IntegrationPrometheusSpec defines the desired state of IntegrationPrometheus
type IntegrationPrometheusSpec struct {
	v2.ManagedResourceSpec `json:",inline"`
	ForProvider            IntegrationPrometheusParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider IntegrationPrometheusInitParameters `json:"initProvider,omitempty"`
}

// IntegrationPrometheusStatus defines the observed state of IntegrationPrometheus.
type IntegrationPrometheusStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        IntegrationPrometheusObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// IntegrationPrometheus is the Schema for the IntegrationPrometheuss API. Creates and manages third party prometheus metrics integration for a CloudAMQP instance.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,cloudamqp}
type IntegrationPrometheus struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	Spec              IntegrationPrometheusSpec   `json:"spec"`
	Status            IntegrationPrometheusStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// IntegrationPrometheusList contains a list of IntegrationPrometheuss
type IntegrationPrometheusList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []IntegrationPrometheus `json:"items"`
}

// Repository type metadata.
var (
	IntegrationPrometheus_Kind             = "IntegrationPrometheus"
	IntegrationPrometheus_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: IntegrationPrometheus_Kind}.String()
	IntegrationPrometheus_KindAPIVersion   = IntegrationPrometheus_Kind + "." + CRDGroupVersion.String()
	IntegrationPrometheus_GroupVersionKind = CRDGroupVersion.WithKind(IntegrationPrometheus_Kind)
)

func init() {
	SchemeBuilder.Register(&IntegrationPrometheus{}, &IntegrationPrometheusList{})
}
