apiVersion: cloudamqp.evaneos.com/v1alpha1
kind: Instance
metadata:
  annotations:
    meta.upbound.io/example-id: cloudamqp/v1alpha1/instance
  labels:
    testing.upbound.io/example-name: lemur_instance
  name: lemur-instance
spec:
  forProvider:
    name: cloudamqp-free-instance-01
    plan: lemming
    region: amazon-web-services::us-west-1
    tags:
    - lavinmq
