apiVersion: cloudamqp.evaneos.com/v1alpha1
kind: MaintenanceWindow
metadata:
  annotations:
    meta.upbound.io/example-id: cloudamqp/v1alpha1/maintenancewindow
  labels:
    testing.upbound.io/example-name: this
  name: this
spec:
  forProvider:
    instanceIdSelector:
      matchLabels:
        testing.upbound.io/example-name: instance
    preferredDay: Monday
    preferredTime: "23:00"
