apiVersion: cloudamqp.evaneos.com/v1alpha1
kind: VpcGCPPeering
metadata:
  annotations:
    meta.upbound.io/example-id: cloudamqp/v1alpha1/vpcgcppeering
  labels:
    testing.upbound.io/example-name: vpc_peering_request
  name: vpc-peering-request
spec:
  forProvider:
    instanceIdSelector:
      matchLabels:
        testing.upbound.io/example-name: instance
    peerNetworkUri: https://www.googleapis.com/compute/v1/projects/PROJECT-NAME/global/networks/VPC-NETWORK-NAME

---

apiVersion: cloudamqp.evaneos.com/v1alpha1
kind: Instance
metadata:
  annotations:
    meta.upbound.io/example-id: cloudamqp/v1alpha1/vpcgcppeering
  labels:
    testing.upbound.io/example-name: instance
  name: instance
spec:
  forProvider:
    name: terraform-vpc-peering
    plan: penguin-1
    region: google-compute-engine::europe-north1
    tags:
    - terraform
    vpcSubnet: 10.40.72.0/24
