// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
)

type IntegrationLogInitParameters struct {

	// The API key.
	// The API key for the integration service. (Datadog)
	APIKeySecretRef *v1.SecretKeySelector `json:"apiKeySecretRef,omitempty" tf:"-"`

	// AWS access key identifier.
	// AWS access key identifier. (Cloudwatch)
	AccessKeyIDSecretRef *v1.SecretKeySelector `json:"accessKeyIdSecretRef,omitempty" tf:"-"`

	// The application name for Coralogix.
	// The name of the application. (Azure Monitor)
	Application *string `json:"application,omitempty" tf:"application,omitempty"`

	// The application identifier.
	// The application ID. (Azure Monitor)
	ApplicationID *string `json:"applicationId,omitempty" tf:"application_id,omitempty"`

	// The application secret.
	// The application secret. (Azure Monitor)
	ApplicationSecretSecretRef *v1.SecretKeySelector `json:"applicationSecretSecretRef,omitempty" tf:"-"`

	// The client email registered for the integration service.
	// The client email. (Stackdriver)
	ClientEmail *string `json:"clientEmail,omitempty" tf:"client_email,omitempty"`

	// Google Service Account private key credentials.
	// Base64Encoded credentials. (Stackdriver)
	CredentialsSecretRef *v1.SecretKeySelector `json:"credentialsSecretRef,omitempty" tf:"-"`

	// The data collection endpoint.
	// The DCE URI. (Coralogix)
	DceURI *string `json:"dceUri,omitempty" tf:"dce_uri,omitempty"`

	// ID of data collection rule that your DCE is linked to.
	// The DCR ID. (Coralogix)
	DcrID *string `json:"dcrId,omitempty" tf:"dcr_id,omitempty"`

	// The syslog destination to send the logs to for Coralogix.
	// The syslog destination to send the logs to. (Papertrail)
	Endpoint *string `json:"endpoint,omitempty" tf:"endpoint,omitempty"`

	// The host for Scalyr integration. Valid hosts app.scalyr.com and
	// app.eu.scalyr.com
	// The host information. (Scalyr)
	Host *string `json:"host,omitempty" tf:"host,omitempty"`

	// Destination to send the logs.
	// Destination to send the logs. (Splunk)
	HostPort *string `json:"hostPort,omitempty" tf:"host_port,omitempty"`

	// Instance identifier for the CloudAMQP instance.
	// Instance identifier
	// +crossplane:generate:reference:type=github.com/evaneos/provider-cloudamqp/apis/cluster/cloudamqp/v1alpha1.Instance
	InstanceID *float64 `json:"instanceId,omitempty" tf:"instance_id,omitempty"`

	// Reference to a Instance in cloudamqp to populate instanceId.
	// +kubebuilder:validation:Optional
	InstanceIDRef *v1.Reference `json:"instanceIdRef,omitempty" tf:"-"`

	// Selector for a Instance in cloudamqp to populate instanceId.
	// +kubebuilder:validation:Optional
	InstanceIDSelector *v1.Selector `json:"instanceIdSelector,omitempty" tf:"-"`

	// The name of the third party log integration (azure_monitoring).
	// The name of log integration
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// The identifier for this resource
	// Private key identifier. (Stackdriver)
	PrivateKeyIDSecretRef *v1.SecretKeySelector `json:"privateKeyIdSecretRef,omitempty" tf:"-"`

	// The private access key.
	// The private API key used for authentication. (Stackdriver, Coralogix)
	PrivateKeySecretRef *v1.SecretKeySelector `json:"privateKeySecretRef,omitempty" tf:"-"`

	// The project identifier.
	// The project ID for the integration service. (Stackdriver)
	ProjectID *string `json:"projectId,omitempty" tf:"project_id,omitempty"`

	// AWS region hosting the integration service.
	// The region hosting integration service. (Cloudwatch, Datadog)
	Region *string `json:"region,omitempty" tf:"region,omitempty"`

	// Number of days to retain log events in CloudAMQP log group.
	// The number of days to retain logs. (Cloudwatch)
	Retention *float64 `json:"retention,omitempty" tf:"retention,omitempty"`

	// AWS secret access key.
	// AWS secret access key. (Cloudwatch)
	SecretAccessKeySecretRef *v1.SecretKeySelector `json:"secretAccessKeySecretRef,omitempty" tf:"-"`

	// Assign source type to the data exported, eg. generic_single_line.
	// Assign source type to the data exported, eg. generic_single_line. (Splunk)
	Sourcetype *string `json:"sourcetype,omitempty" tf:"sourcetype,omitempty"`

	// The subsystem name for Coralogix.
	// The name of the subsystem. (Azure Monitor)
	Subsystem *string `json:"subsystem,omitempty" tf:"subsystem,omitempty"`

	// The table name.
	// The table name to send the logs to. (Azure Monitor)
	Table *string `json:"table,omitempty" tf:"table,omitempty"`

	// Enter tags to CloudAMQP log group like this: Project=A,Environment=Development.
	// Optional tags. E.g. env=prod,region=europe. (Cloudwatch, Datadog)
	Tags *string `json:"tags,omitempty" tf:"tags,omitempty"`

	// The tenant identifier.
	// The tenant ID. (Azure Monitor)
	TenantID *string `json:"tenantId,omitempty" tf:"tenant_id,omitempty"`

	// Token used for authentication.
	// The token used for authentication. (Loggly, Logentries, Splunk, Scalyr)
	TokenSecretRef *v1.SecretKeySelector `json:"tokenSecretRef,omitempty" tf:"-"`

	// Endpoint to log integration.
	// The URL to push the logs to. (Papertrail)
	URL *string `json:"url,omitempty" tf:"url,omitempty"`
}

type IntegrationLogObservation struct {

	// The application name for Coralogix.
	// The name of the application. (Azure Monitor)
	Application *string `json:"application,omitempty" tf:"application,omitempty"`

	// The application identifier.
	// The application ID. (Azure Monitor)
	ApplicationID *string `json:"applicationId,omitempty" tf:"application_id,omitempty"`

	// The client email registered for the integration service.
	// The client email. (Stackdriver)
	ClientEmail *string `json:"clientEmail,omitempty" tf:"client_email,omitempty"`

	// The data collection endpoint.
	// The DCE URI. (Coralogix)
	DceURI *string `json:"dceUri,omitempty" tf:"dce_uri,omitempty"`

	// ID of data collection rule that your DCE is linked to.
	// The DCR ID. (Coralogix)
	DcrID *string `json:"dcrId,omitempty" tf:"dcr_id,omitempty"`

	// The syslog destination to send the logs to for Coralogix.
	// The syslog destination to send the logs to. (Papertrail)
	Endpoint *string `json:"endpoint,omitempty" tf:"endpoint,omitempty"`

	// The host for Scalyr integration. Valid hosts app.scalyr.com and
	// app.eu.scalyr.com
	// The host information. (Scalyr)
	Host *string `json:"host,omitempty" tf:"host,omitempty"`

	// Destination to send the logs.
	// Destination to send the logs. (Splunk)
	HostPort *string `json:"hostPort,omitempty" tf:"host_port,omitempty"`

	// The identifier for this resource
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// Instance identifier for the CloudAMQP instance.
	// Instance identifier
	InstanceID *float64 `json:"instanceId,omitempty" tf:"instance_id,omitempty"`

	// The name of the third party log integration (azure_monitoring).
	// The name of log integration
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// The project identifier.
	// The project ID for the integration service. (Stackdriver)
	ProjectID *string `json:"projectId,omitempty" tf:"project_id,omitempty"`

	// AWS region hosting the integration service.
	// The region hosting integration service. (Cloudwatch, Datadog)
	Region *string `json:"region,omitempty" tf:"region,omitempty"`

	// Number of days to retain log events in CloudAMQP log group.
	// The number of days to retain logs. (Cloudwatch)
	Retention *float64 `json:"retention,omitempty" tf:"retention,omitempty"`

	// Assign source type to the data exported, eg. generic_single_line.
	// Assign source type to the data exported, eg. generic_single_line. (Splunk)
	Sourcetype *string `json:"sourcetype,omitempty" tf:"sourcetype,omitempty"`

	// The subsystem name for Coralogix.
	// The name of the subsystem. (Azure Monitor)
	Subsystem *string `json:"subsystem,omitempty" tf:"subsystem,omitempty"`

	// The table name.
	// The table name to send the logs to. (Azure Monitor)
	Table *string `json:"table,omitempty" tf:"table,omitempty"`

	// Enter tags to CloudAMQP log group like this: Project=A,Environment=Development.
	// Optional tags. E.g. env=prod,region=europe. (Cloudwatch, Datadog)
	Tags *string `json:"tags,omitempty" tf:"tags,omitempty"`

	// The tenant identifier.
	// The tenant ID. (Azure Monitor)
	TenantID *string `json:"tenantId,omitempty" tf:"tenant_id,omitempty"`

	// Endpoint to log integration.
	// The URL to push the logs to. (Papertrail)
	URL *string `json:"url,omitempty" tf:"url,omitempty"`
}

type IntegrationLogParameters struct {

	// The API key.
	// The API key for the integration service. (Datadog)
	// +kubebuilder:validation:Optional
	APIKeySecretRef *v1.SecretKeySelector `json:"apiKeySecretRef,omitempty" tf:"-"`

	// AWS access key identifier.
	// AWS access key identifier. (Cloudwatch)
	// +kubebuilder:validation:Optional
	AccessKeyIDSecretRef *v1.SecretKeySelector `json:"accessKeyIdSecretRef,omitempty" tf:"-"`

	// The application name for Coralogix.
	// The name of the application. (Azure Monitor)
	// +kubebuilder:validation:Optional
	Application *string `json:"application,omitempty" tf:"application,omitempty"`

	// The application identifier.
	// The application ID. (Azure Monitor)
	// +kubebuilder:validation:Optional
	ApplicationID *string `json:"applicationId,omitempty" tf:"application_id,omitempty"`

	// The application secret.
	// The application secret. (Azure Monitor)
	// +kubebuilder:validation:Optional
	ApplicationSecretSecretRef *v1.SecretKeySelector `json:"applicationSecretSecretRef,omitempty" tf:"-"`

	// The client email registered for the integration service.
	// The client email. (Stackdriver)
	// +kubebuilder:validation:Optional
	ClientEmail *string `json:"clientEmail,omitempty" tf:"client_email,omitempty"`

	// Google Service Account private key credentials.
	// Base64Encoded credentials. (Stackdriver)
	// +kubebuilder:validation:Optional
	CredentialsSecretRef *v1.SecretKeySelector `json:"credentialsSecretRef,omitempty" tf:"-"`

	// The data collection endpoint.
	// The DCE URI. (Coralogix)
	// +kubebuilder:validation:Optional
	DceURI *string `json:"dceUri,omitempty" tf:"dce_uri,omitempty"`

	// ID of data collection rule that your DCE is linked to.
	// The DCR ID. (Coralogix)
	// +kubebuilder:validation:Optional
	DcrID *string `json:"dcrId,omitempty" tf:"dcr_id,omitempty"`

	// The syslog destination to send the logs to for Coralogix.
	// The syslog destination to send the logs to. (Papertrail)
	// +kubebuilder:validation:Optional
	Endpoint *string `json:"endpoint,omitempty" tf:"endpoint,omitempty"`

	// The host for Scalyr integration. Valid hosts app.scalyr.com and
	// app.eu.scalyr.com
	// The host information. (Scalyr)
	// +kubebuilder:validation:Optional
	Host *string `json:"host,omitempty" tf:"host,omitempty"`

	// Destination to send the logs.
	// Destination to send the logs. (Splunk)
	// +kubebuilder:validation:Optional
	HostPort *string `json:"hostPort,omitempty" tf:"host_port,omitempty"`

	// Instance identifier for the CloudAMQP instance.
	// Instance identifier
	// +crossplane:generate:reference:type=github.com/evaneos/provider-cloudamqp/apis/cluster/cloudamqp/v1alpha1.Instance
	// +kubebuilder:validation:Optional
	InstanceID *float64 `json:"instanceId,omitempty" tf:"instance_id,omitempty"`

	// Reference to a Instance in cloudamqp to populate instanceId.
	// +kubebuilder:validation:Optional
	InstanceIDRef *v1.Reference `json:"instanceIdRef,omitempty" tf:"-"`

	// Selector for a Instance in cloudamqp to populate instanceId.
	// +kubebuilder:validation:Optional
	InstanceIDSelector *v1.Selector `json:"instanceIdSelector,omitempty" tf:"-"`

	// The name of the third party log integration (azure_monitoring).
	// The name of log integration
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// The identifier for this resource
	// Private key identifier. (Stackdriver)
	// +kubebuilder:validation:Optional
	PrivateKeyIDSecretRef *v1.SecretKeySelector `json:"privateKeyIdSecretRef,omitempty" tf:"-"`

	// The private access key.
	// The private API key used for authentication. (Stackdriver, Coralogix)
	// +kubebuilder:validation:Optional
	PrivateKeySecretRef *v1.SecretKeySelector `json:"privateKeySecretRef,omitempty" tf:"-"`

	// The project identifier.
	// The project ID for the integration service. (Stackdriver)
	// +kubebuilder:validation:Optional
	ProjectID *string `json:"projectId,omitempty" tf:"project_id,omitempty"`

	// AWS region hosting the integration service.
	// The region hosting integration service. (Cloudwatch, Datadog)
	// +kubebuilder:validation:Optional
	Region *string `json:"region,omitempty" tf:"region,omitempty"`

	// Number of days to retain log events in CloudAMQP log group.
	// The number of days to retain logs. (Cloudwatch)
	// +kubebuilder:validation:Optional
	Retention *float64 `json:"retention,omitempty" tf:"retention,omitempty"`

	// AWS secret access key.
	// AWS secret access key. (Cloudwatch)
	// +kubebuilder:validation:Optional
	SecretAccessKeySecretRef *v1.SecretKeySelector `json:"secretAccessKeySecretRef,omitempty" tf:"-"`

	// Assign source type to the data exported, eg. generic_single_line.
	// Assign source type to the data exported, eg. generic_single_line. (Splunk)
	// +kubebuilder:validation:Optional
	Sourcetype *string `json:"sourcetype,omitempty" tf:"sourcetype,omitempty"`

	// The subsystem name for Coralogix.
	// The name of the subsystem. (Azure Monitor)
	// +kubebuilder:validation:Optional
	Subsystem *string `json:"subsystem,omitempty" tf:"subsystem,omitempty"`

	// The table name.
	// The table name to send the logs to. (Azure Monitor)
	// +kubebuilder:validation:Optional
	Table *string `json:"table,omitempty" tf:"table,omitempty"`

	// Enter tags to CloudAMQP log group like this: Project=A,Environment=Development.
	// Optional tags. E.g. env=prod,region=europe. (Cloudwatch, Datadog)
	// +kubebuilder:validation:Optional
	Tags *string `json:"tags,omitempty" tf:"tags,omitempty"`

	// The tenant identifier.
	// The tenant ID. (Azure Monitor)
	// +kubebuilder:validation:Optional
	TenantID *string `json:"tenantId,omitempty" tf:"tenant_id,omitempty"`

	// Token used for authentication.
	// The token used for authentication. (Loggly, Logentries, Splunk, Scalyr)
	// +kubebuilder:validation:Optional
	TokenSecretRef *v1.SecretKeySelector `json:"tokenSecretRef,omitempty" tf:"-"`

	// Endpoint to log integration.
	// The URL to push the logs to. (Papertrail)
	// +kubebuilder:validation:Optional
	URL *string `json:"url,omitempty" tf:"url,omitempty"`
}

// IntegrationLogSpec defines the desired state of IntegrationLog
type IntegrationLogSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     IntegrationLogParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider IntegrationLogInitParameters `json:"initProvider,omitempty"`
}

// IntegrationLogStatus defines the observed state of IntegrationLog.
type IntegrationLogStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        IntegrationLogObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// IntegrationLog is the Schema for the IntegrationLogs API. Creates and manages third party log integration for a CloudAMQP instance.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,cloudamqp}
type IntegrationLog struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.name) || (has(self.initProvider) && has(self.initProvider.name))",message="spec.forProvider.name is a required parameter"
	Spec   IntegrationLogSpec   `json:"spec"`
	Status IntegrationLogStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// IntegrationLogList contains a list of IntegrationLogs
type IntegrationLogList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []IntegrationLog `json:"items"`
}

// Repository type metadata.
var (
	IntegrationLog_Kind             = "IntegrationLog"
	IntegrationLog_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: IntegrationLog_Kind}.String()
	IntegrationLog_KindAPIVersion   = IntegrationLog_Kind + "." + CRDGroupVersion.String()
	IntegrationLog_GroupVersionKind = CRDGroupVersion.WithKind(IntegrationLog_Kind)
)

func init() {
	SchemeBuilder.Register(&IntegrationLog{}, &IntegrationLogList{})
}
