// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
)

type MetricInitParameters struct {

	// The API key for the integration service.
	// The API key for the integration service. (Librato)
	APIKeySecretRef *v1.SecretKeySelector `json:"apiKeySecretRef,omitempty" tf:"-"`

	// AWS access key identifier.
	// AWS access key identifier. (Cloudwatch)
	AccessKeyID *string `json:"accessKeyId,omitempty" tf:"access_key_id,omitempty"`

	// The client email registered for the integration service.
	// The client email. (Stackdriver)
	ClientEmail *string `json:"clientEmail,omitempty" tf:"client_email,omitempty"`

	// Google Service Account private key credentials.
	// Base64Encoded credentials. (Stackdriver)
	CredentialsSecretRef *v1.SecretKeySelector `json:"credentialsSecretRef,omitempty" tf:"-"`

	// The email address registred for the integration service.
	// The email address registred for the integration service. (Librato)
	Email *string `json:"email,omitempty" tf:"email,omitempty"`

	// External identifier that match the role you created.
	// External identifier that match the role you created. (Cloudwatch)
	IAMExternalID *string `json:"iamExternalId,omitempty" tf:"iam_external_id,omitempty"`

	// The ARN of the role to be assumed when publishing metrics.
	// The ARN of the role to be assumed when publishing metrics. (Cloudwatch)
	IAMRole *string `json:"iamRole,omitempty" tf:"iam_role,omitempty"`

	// Include auto delete queues.
	// (optional) Include Auto-Delete queues
	IncludeAdQueues *bool `json:"includeAdQueues,omitempty" tf:"include_ad_queues,omitempty"`

	// The identifier for this resource.
	// Instance identifier
	// +crossplane:generate:reference:type=github.com/evaneos/provider-cloudamqp/apis/cluster/cloudamqp/v1alpha1.Instance
	InstanceID *float64 `json:"instanceId,omitempty" tf:"instance_id,omitempty"`

	// Reference to a Instance in cloudamqp to populate instanceId.
	// +kubebuilder:validation:Optional
	InstanceIDRef *v1.Reference `json:"instanceIdRef,omitempty" tf:"-"`

	// Selector for a Instance in cloudamqp to populate instanceId.
	// +kubebuilder:validation:Optional
	InstanceIDSelector *v1.Selector `json:"instanceIdSelector,omitempty" tf:"-"`

	// The license key registred for the integration service. (New Relic)
	LicenseKeySecretRef *v1.SecretKeySelector `json:"licenseKeySecretRef,omitempty" tf:"-"`

	// The name of the third party log integration. See
	// Integration service reference
	// The name of metrics integration
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// The identifier for this resource.
	// Private key identifier. (Stackdriver)
	PrivateKeyIDSecretRef *v1.SecretKeySelector `json:"privateKeyIdSecretRef,omitempty" tf:"-"`

	// The private access key.
	// The private key. (Stackdriver)
	PrivateKeySecretRef *v1.SecretKeySelector `json:"privateKeySecretRef,omitempty" tf:"-"`

	// The project identifier.
	// Project ID. (Stackdriver)
	ProjectID *string `json:"projectId,omitempty" tf:"project_id,omitempty"`

	// Allowlist queues using regular expression. Leave empty to include
	// all queues.
	// (optional) allowlist using regular expression
	QueueAllowlist *string `json:"queueAllowlist,omitempty" tf:"queue_allowlist,omitempty"`

	// Deprecated Use queue_allowlist instead
	// **Deprecated**
	QueueWhitelist *string `json:"queueWhitelist,omitempty" tf:"queue_whitelist,omitempty"`

	// Region hosting the integration service.
	// AWS region for Cloudwatch and [US/EU] for Data dog/New relic. (Cloudwatch, Data Dog, New Relic)
	Region *string `json:"region,omitempty" tf:"region,omitempty"`

	// AWS secret access key.
	// AWS secret key. (Cloudwatch)
	SecretAccessKeySecretRef *v1.SecretKeySelector `json:"secretAccessKeySecretRef,omitempty" tf:"-"`

	// Tags. e.g. env=prod,region=europe.
	// (optional) tags. E.g. env=prod,region=europe
	Tags *string `json:"tags,omitempty" tf:"tags,omitempty"`

	// Allowlist vhost using regular expression. Leave empty to include
	// all vhosts.
	// (optional) allowlist using regular expression
	VhostAllowlist *string `json:"vhostAllowlist,omitempty" tf:"vhost_allowlist,omitempty"`

	// Deprecated Use vhost_allowlist instead
	// **Deprecated**
	VhostWhitelist *string `json:"vhostWhitelist,omitempty" tf:"vhost_whitelist,omitempty"`
}

type MetricObservation struct {

	// AWS access key identifier.
	// AWS access key identifier. (Cloudwatch)
	AccessKeyID *string `json:"accessKeyId,omitempty" tf:"access_key_id,omitempty"`

	// The client email registered for the integration service.
	// The client email. (Stackdriver)
	ClientEmail *string `json:"clientEmail,omitempty" tf:"client_email,omitempty"`

	// The email address registred for the integration service.
	// The email address registred for the integration service. (Librato)
	Email *string `json:"email,omitempty" tf:"email,omitempty"`

	// External identifier that match the role you created.
	// External identifier that match the role you created. (Cloudwatch)
	IAMExternalID *string `json:"iamExternalId,omitempty" tf:"iam_external_id,omitempty"`

	// The ARN of the role to be assumed when publishing metrics.
	// The ARN of the role to be assumed when publishing metrics. (Cloudwatch)
	IAMRole *string `json:"iamRole,omitempty" tf:"iam_role,omitempty"`

	// The identifier for this resource.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// Include auto delete queues.
	// (optional) Include Auto-Delete queues
	IncludeAdQueues *bool `json:"includeAdQueues,omitempty" tf:"include_ad_queues,omitempty"`

	// The identifier for this resource.
	// Instance identifier
	InstanceID *float64 `json:"instanceId,omitempty" tf:"instance_id,omitempty"`

	// The name of the third party log integration. See
	// Integration service reference
	// The name of metrics integration
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// The project identifier.
	// Project ID. (Stackdriver)
	ProjectID *string `json:"projectId,omitempty" tf:"project_id,omitempty"`

	// Allowlist queues using regular expression. Leave empty to include
	// all queues.
	// (optional) allowlist using regular expression
	QueueAllowlist *string `json:"queueAllowlist,omitempty" tf:"queue_allowlist,omitempty"`

	// Deprecated Use queue_allowlist instead
	// **Deprecated**
	QueueWhitelist *string `json:"queueWhitelist,omitempty" tf:"queue_whitelist,omitempty"`

	// Region hosting the integration service.
	// AWS region for Cloudwatch and [US/EU] for Data dog/New relic. (Cloudwatch, Data Dog, New Relic)
	Region *string `json:"region,omitempty" tf:"region,omitempty"`

	// Tags. e.g. env=prod,region=europe.
	// (optional) tags. E.g. env=prod,region=europe
	Tags *string `json:"tags,omitempty" tf:"tags,omitempty"`

	// Allowlist vhost using regular expression. Leave empty to include
	// all vhosts.
	// (optional) allowlist using regular expression
	VhostAllowlist *string `json:"vhostAllowlist,omitempty" tf:"vhost_allowlist,omitempty"`

	// Deprecated Use vhost_allowlist instead
	// **Deprecated**
	VhostWhitelist *string `json:"vhostWhitelist,omitempty" tf:"vhost_whitelist,omitempty"`
}

type MetricParameters struct {

	// The API key for the integration service.
	// The API key for the integration service. (Librato)
	// +kubebuilder:validation:Optional
	APIKeySecretRef *v1.SecretKeySelector `json:"apiKeySecretRef,omitempty" tf:"-"`

	// AWS access key identifier.
	// AWS access key identifier. (Cloudwatch)
	// +kubebuilder:validation:Optional
	AccessKeyID *string `json:"accessKeyId,omitempty" tf:"access_key_id,omitempty"`

	// The client email registered for the integration service.
	// The client email. (Stackdriver)
	// +kubebuilder:validation:Optional
	ClientEmail *string `json:"clientEmail,omitempty" tf:"client_email,omitempty"`

	// Google Service Account private key credentials.
	// Base64Encoded credentials. (Stackdriver)
	// +kubebuilder:validation:Optional
	CredentialsSecretRef *v1.SecretKeySelector `json:"credentialsSecretRef,omitempty" tf:"-"`

	// The email address registred for the integration service.
	// The email address registred for the integration service. (Librato)
	// +kubebuilder:validation:Optional
	Email *string `json:"email,omitempty" tf:"email,omitempty"`

	// External identifier that match the role you created.
	// External identifier that match the role you created. (Cloudwatch)
	// +kubebuilder:validation:Optional
	IAMExternalID *string `json:"iamExternalId,omitempty" tf:"iam_external_id,omitempty"`

	// The ARN of the role to be assumed when publishing metrics.
	// The ARN of the role to be assumed when publishing metrics. (Cloudwatch)
	// +kubebuilder:validation:Optional
	IAMRole *string `json:"iamRole,omitempty" tf:"iam_role,omitempty"`

	// Include auto delete queues.
	// (optional) Include Auto-Delete queues
	// +kubebuilder:validation:Optional
	IncludeAdQueues *bool `json:"includeAdQueues,omitempty" tf:"include_ad_queues,omitempty"`

	// The identifier for this resource.
	// Instance identifier
	// +crossplane:generate:reference:type=github.com/evaneos/provider-cloudamqp/apis/cluster/cloudamqp/v1alpha1.Instance
	// +kubebuilder:validation:Optional
	InstanceID *float64 `json:"instanceId,omitempty" tf:"instance_id,omitempty"`

	// Reference to a Instance in cloudamqp to populate instanceId.
	// +kubebuilder:validation:Optional
	InstanceIDRef *v1.Reference `json:"instanceIdRef,omitempty" tf:"-"`

	// Selector for a Instance in cloudamqp to populate instanceId.
	// +kubebuilder:validation:Optional
	InstanceIDSelector *v1.Selector `json:"instanceIdSelector,omitempty" tf:"-"`

	// The license key registred for the integration service. (New Relic)
	// +kubebuilder:validation:Optional
	LicenseKeySecretRef *v1.SecretKeySelector `json:"licenseKeySecretRef,omitempty" tf:"-"`

	// The name of the third party log integration. See
	// Integration service reference
	// The name of metrics integration
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// The identifier for this resource.
	// Private key identifier. (Stackdriver)
	// +kubebuilder:validation:Optional
	PrivateKeyIDSecretRef *v1.SecretKeySelector `json:"privateKeyIdSecretRef,omitempty" tf:"-"`

	// The private access key.
	// The private key. (Stackdriver)
	// +kubebuilder:validation:Optional
	PrivateKeySecretRef *v1.SecretKeySelector `json:"privateKeySecretRef,omitempty" tf:"-"`

	// The project identifier.
	// Project ID. (Stackdriver)
	// +kubebuilder:validation:Optional
	ProjectID *string `json:"projectId,omitempty" tf:"project_id,omitempty"`

	// Allowlist queues using regular expression. Leave empty to include
	// all queues.
	// (optional) allowlist using regular expression
	// +kubebuilder:validation:Optional
	QueueAllowlist *string `json:"queueAllowlist,omitempty" tf:"queue_allowlist,omitempty"`

	// Deprecated Use queue_allowlist instead
	// **Deprecated**
	// +kubebuilder:validation:Optional
	QueueWhitelist *string `json:"queueWhitelist,omitempty" tf:"queue_whitelist,omitempty"`

	// Region hosting the integration service.
	// AWS region for Cloudwatch and [US/EU] for Data dog/New relic. (Cloudwatch, Data Dog, New Relic)
	// +kubebuilder:validation:Optional
	Region *string `json:"region,omitempty" tf:"region,omitempty"`

	// AWS secret access key.
	// AWS secret key. (Cloudwatch)
	// +kubebuilder:validation:Optional
	SecretAccessKeySecretRef *v1.SecretKeySelector `json:"secretAccessKeySecretRef,omitempty" tf:"-"`

	// Tags. e.g. env=prod,region=europe.
	// (optional) tags. E.g. env=prod,region=europe
	// +kubebuilder:validation:Optional
	Tags *string `json:"tags,omitempty" tf:"tags,omitempty"`

	// Allowlist vhost using regular expression. Leave empty to include
	// all vhosts.
	// (optional) allowlist using regular expression
	// +kubebuilder:validation:Optional
	VhostAllowlist *string `json:"vhostAllowlist,omitempty" tf:"vhost_allowlist,omitempty"`

	// Deprecated Use vhost_allowlist instead
	// **Deprecated**
	// +kubebuilder:validation:Optional
	VhostWhitelist *string `json:"vhostWhitelist,omitempty" tf:"vhost_whitelist,omitempty"`
}

// MetricSpec defines the desired state of Metric
type MetricSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     MetricParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider MetricInitParameters `json:"initProvider,omitempty"`
}

// MetricStatus defines the observed state of Metric.
type MetricStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        MetricObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// Metric is the Schema for the Metrics API. Creates and manages third party metrics integration for a CloudAMQP instance.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,cloudamqp}
type Metric struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.name) || (has(self.initProvider) && has(self.initProvider.name))",message="spec.forProvider.name is a required parameter"
	Spec   MetricSpec   `json:"spec"`
	Status MetricStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// MetricList contains a list of Metrics
type MetricList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []Metric `json:"items"`
}

// Repository type metadata.
var (
	Metric_Kind             = "Metric"
	Metric_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: Metric_Kind}.String()
	Metric_KindAPIVersion   = Metric_Kind + "." + CRDGroupVersion.String()
	Metric_GroupVersionKind = CRDGroupVersion.WithKind(Metric_Kind)
)

func init() {
	SchemeBuilder.Register(&Metric{}, &MetricList{})
}
