apiVersion: cloudamqp.evaneos.com/v1alpha1
kind: Instance
metadata:
  name: cloudamqp-instance
spec:
  forProvider:
    name: test
    plan: lemur
    region: google-compute-engine::europe-west1
  providerConfigRef:
    name: default